// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heart_beat.proto

#ifndef PROTOBUF_INCLUDED_heart_5fbeat_2eproto
#define PROTOBUF_INCLUDED_heart_5fbeat_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_heart_5fbeat_2eproto 

namespace protobuf_heart_5fbeat_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_heart_5fbeat_2eproto
namespace game {
class ReqHeart;
class ReqHeartDefaultTypeInternal;
extern ReqHeartDefaultTypeInternal _ReqHeart_default_instance_;
class ResHeart;
class ResHeartDefaultTypeInternal;
extern ResHeartDefaultTypeInternal _ResHeart_default_instance_;
}  // namespace game
namespace google {
namespace protobuf {
template<> ::game::ReqHeart* Arena::CreateMaybeMessage<::game::ReqHeart>(Arena*);
template<> ::game::ResHeart* Arena::CreateMaybeMessage<::game::ResHeart>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace game {

// ===================================================================

class ReqHeart : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:game.ReqHeart) */ {
 public:
  ReqHeart();
  virtual ~ReqHeart();

  ReqHeart(const ReqHeart& from);

  inline ReqHeart& operator=(const ReqHeart& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ReqHeart(ReqHeart&& from) noexcept
    : ReqHeart() {
    *this = ::std::move(from);
  }

  inline ReqHeart& operator=(ReqHeart&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ReqHeart& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReqHeart* internal_default_instance() {
    return reinterpret_cast<const ReqHeart*>(
               &_ReqHeart_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ReqHeart* other);
  friend void swap(ReqHeart& a, ReqHeart& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReqHeart* New() const final {
    return CreateMaybeMessage<ReqHeart>(NULL);
  }

  ReqHeart* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ReqHeart>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ReqHeart& from);
  void MergeFrom(const ReqHeart& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReqHeart* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 msg_id = 1;
  void clear_msg_id();
  static const int kMsgIdFieldNumber = 1;
  ::google::protobuf::int32 msg_id() const;
  void set_msg_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:game.ReqHeart)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 msg_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_heart_5fbeat_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ResHeart : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:game.ResHeart) */ {
 public:
  ResHeart();
  virtual ~ResHeart();

  ResHeart(const ResHeart& from);

  inline ResHeart& operator=(const ResHeart& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ResHeart(ResHeart&& from) noexcept
    : ResHeart() {
    *this = ::std::move(from);
  }

  inline ResHeart& operator=(ResHeart&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ResHeart& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResHeart* internal_default_instance() {
    return reinterpret_cast<const ResHeart*>(
               &_ResHeart_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ResHeart* other);
  friend void swap(ResHeart& a, ResHeart& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ResHeart* New() const final {
    return CreateMaybeMessage<ResHeart>(NULL);
  }

  ResHeart* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ResHeart>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ResHeart& from);
  void MergeFrom(const ResHeart& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResHeart* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 msg_id = 1;
  void clear_msg_id();
  static const int kMsgIdFieldNumber = 1;
  ::google::protobuf::int32 msg_id() const;
  void set_msg_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:game.ResHeart)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 msg_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_heart_5fbeat_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ReqHeart

// int32 msg_id = 1;
inline void ReqHeart::clear_msg_id() {
  msg_id_ = 0;
}
inline ::google::protobuf::int32 ReqHeart::msg_id() const {
  // @@protoc_insertion_point(field_get:game.ReqHeart.msg_id)
  return msg_id_;
}
inline void ReqHeart::set_msg_id(::google::protobuf::int32 value) {
  
  msg_id_ = value;
  // @@protoc_insertion_point(field_set:game.ReqHeart.msg_id)
}

// -------------------------------------------------------------------

// ResHeart

// int32 msg_id = 1;
inline void ResHeart::clear_msg_id() {
  msg_id_ = 0;
}
inline ::google::protobuf::int32 ResHeart::msg_id() const {
  // @@protoc_insertion_point(field_get:game.ResHeart.msg_id)
  return msg_id_;
}
inline void ResHeart::set_msg_id(::google::protobuf::int32 value) {
  
  msg_id_ = value;
  // @@protoc_insertion_point(field_set:game.ResHeart.msg_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace game

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_heart_5fbeat_2eproto
